---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-controller
  namespace: flux-system
spec:
  interval: 24h
  type: oci
  url: oci://registry-1.docker.io/envoyproxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-controller
  namespace: flux-system
spec:
  targetNamespace: envoy-gateway-system
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: gateway-helm
      version: "v1.0.1"
      sourceRef:
        kind: HelmRepository
        name: envoy-controller
        namespace: flux-system
  values:
    config:
      envoyGateway:
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller