apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: our-little-corner
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: "./k8s"
  prune: true
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: our-little-corner
  namespace: flux-system
spec:
  image: ghcr.io/alexfirilolv/our_little_corner
  interval: 5m
  secretRef:
    name: ghcr-secret
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: our-little-corner
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: our-little-corner
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^[0-9]+$'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: our-little-corner
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: "./k8s"
    strategy: Setters